# Generated by Django 2.2.3 on 2019-07-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='manu_date',
            new_name='menu_date',
        ),
    ]
