# Generated by Django 2.2.3 on 2019-07-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190724_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customization',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
