# Generated by Django 2.2.3 on 2019-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190724_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customization',
            field=models.TextField(null=True),
        ),
    ]
