# Generated by Django 2.2.3 on 2019-07-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='employee',
            field=models.BooleanField(default=True),
        ),
    ]
