# Generated by Django 2.2.3 on 2019-07-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190724_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='city',
            new_name='country',
        ),
    ]
